### PR TITLE
Ss rf firestone

### PR DESCRIPTION
**Pull request by snsebro**
_For an example of how to fill this template out, [see this Pull Request](https://github.com/the-collab-lab/tcl-3-smart-shopping-list/pull/44)._ 

## Description

Updated dependencies added in `firebase` & `react-firestore`
Created firebase folder with firebase.js file to test db connection
Added a component `counter` to show db connection on frontend

## Acceptance Criteria

- [x] The following have been added as project dependencies: firebase & react-firestore
- [x] Make a change in the Firestore database and it shows up in the app
- [x] Make a change in the app and it shows up in the Firestore database

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|    | :bug: Bug fix              |
|  ✓ | :sparkles: New feature     |
|    | :hammer: Refactoring       |
|    | :100: Add tests            |
|  ✓  | :link: Update dependencies |
|    | :scroll: Docs              |

## Updates

- Updated dependencies added in `firebase` & `react-firestore`
- Created firebase folder with firebase.js file to test db connection
- Added a component `counter` to show db connection on frontend

### Before
Default React
image

### After
Buttons added at bottom to show db functionality
image

Firestore Console can be used to view current db entires or edit entries using the web interface
image

## Testing Steps / QA Criteria
If testing from terminal cd into firebase directory and run "node firebase.js" the below message should appear
image

If testing from frontend clicking the "count + " button should increase the count displayed and clicking the "count - " button should decrease the count displayed, and clicking the "get count from db" button should console log the current count in the database
image

### CODE REVIEW

**Comment by rbompiani** [comment]
Looks great!  Nice work.  
The counter resets to 0 when refreshing the app - still pushes to an updates the database with the button clicks.

**Comment by rachel-fischoff** [comment]
@snsebro do you want to work on the issue that @rbompiani mentioned below later today before the mentors review it?
> Looks great! Nice work.
> The counter resets to 0 when refreshing the app - still pushes to and updates the database with the button clicks.

**Comment by rbompiani** [comment]
> @snsebro do you want to work on the issue that @rbompiani mentioned below later today before the mentors review it?
> 
> > Looks great! Nice work.
> > The counter resets to 0 when refreshing the app - still pushes to and updates the database with the button clicks.

I don't necessarily think you guys need to "fix" anything. We had firebase open when we were using the app, and saw that the counter was definitely writing to the database. Initializing state by pulling current items from the database is quite possibly a future task. I'd say that you guys have definitely hit the intent of this story.  Sorry for the confusion!

**Comment by indiragp** [comment]
> Looks great! Nice work.
> The counter resets to 0 when refreshing the app - still pushes to an updates the database with the button clicks.

This is a great comment and a good thing to keep in mind when we have another feature that integrates with the backend, since the point of having a database is to be able to load the page initially with whatever you have in the database and being able to login on a different machine and see the same result :)

**Review by indiragp — APPROVED** [review]
Looks good to me! Great job

**Pull request merged**
